refactor algorithm
ps3611/hoolihomes pull request #6
Opened 2018-10-11 16:42 UTC by ps3611

refactoring structure of algorithm folder
works nicely

2018-10-11 17:26 UTC, alvaroha1 commented on algorithm/index.js
>      formattedObj.country = obj.country;
This means we can filter by country?

2018-10-12 08:12 UTC, ps3611 commented on algorithm/index.js
>      formattedObj.country = obj.country;
no, red means i removed it

2018-10-12 08:13 UTC, ps3611 commented on algorithm/index.js
>      formattedObj.country = obj.country;
yes, country stays

2018-10-12 08:13 UTC, stevenspyramid commented on algorithm/index.js
>      formattedObj.thumbnail = obj.thumbnail;
please change the syntax to a destructuring syntax e.i. const formattedObj = {thumbnail, price, size, country};

2018-10-12 08:14 UTC, stevenvana requested changes
please change the syntax of formattedObj

2018-10-12 08:23 UTC, stevenvana approved these changes
great work!

2018-10-12 08:24 UTC, merged